
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MaerskLineDDAC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Book
{

    public int BookId { get; set; }

    public string Agent { get; set; }

    public int Cargo { get; set; }

    public int Ship { get; set; }

    public int Warehouse { get; set; }



    public virtual Cargo Cargo1 { get; set; }

    public virtual Ship Ship1 { get; set; }

    public virtual Warehouse Warehouse1 { get; set; }

}

}
