
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MaerskLineDDAC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cargo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cargo()
    {

        this.Books = new HashSet<Book>();

    }


    public int CargoId { get; set; }

    public string CargoName { get; set; }

    public Nullable<double> CargoLength { get; set; }

    public Nullable<double> CargoWidth { get; set; }

    public Nullable<double> CargoHeight { get; set; }

    public Nullable<double> CargoWeight { get; set; }

    public string CargoStatus { get; set; }

    public int Customer { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Book> Books { get; set; }

    public virtual Customer Customer1 { get; set; }

}

}
