
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MaerskLineDDAC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Warehouse
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Warehouse()
    {

        this.Books = new HashSet<Book>();

    }


    public int WarehouseId { get; set; }

    public string WarehouseName { get; set; }

    public string WarehouseAddress { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Book> Books { get; set; }

}

}
